export { default as Footer } from "./Footer/Footer"
export { default as Nav } from "./Nav/Nav"
export { default as Profile } from "./Profile/Profile"
export { default as Projects } from "./Projects/Projects"
export { default as Project } from "./Project/Project"